### ISSUE TITLE
استفاده از پلاگین تلگرام

### ISSUE THREAD

**Issue by Adamak90** [MrMahdi313/BaLugin#1]
سلام خسته نباشید 
میخواستم بدونم توی این سورس میشه از پلاگین های تلگرام که با زبان لوا استفاده کرد یا حتما باید به پی اچ پی تبدیل بشه ؟

**Comment by MrMahdi313** [comment]
Plaese see project's language.
This prjoect language is python and you can't use other languages.
But you can generally use the [lupa](https://github.com/scoder/lupa) to use lua in python.
------------------------------------------------------------------------------------------------------------------------------------------------------
لطفا به زبان پروژه در گیت هاب توجه کنید.
این پروژه برای زبان پایتون توسعه داده شده و شما نمیتونید از سایر زبان ها استفاده کنید
اما به طور کلی میتونید از 
 [lupa](https://github.com/scoder/lupa)  
برای استفاده لوا در پایتون بهره ببرید.
